jbtronics_settings:
  default_storage_adapter: Jbtronics\SettingsBundle\Storage\ORMStorageAdapter

  cache:
    default_cacheable: true

  orm_storage:
    default_entity_class: App\Entity\SettingsEntry